import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/layout/Header";
import { jetbrainsMono } from "./fonts";
import SmoothScrolling from "@/utils/SmoothScrolling";
import AnimatePresenceRoot from "@/components/animations/AnimatePresenceRoot";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.className} `}>
        <Header />
        <SmoothScrolling>
          <AnimatePresenceRoot>{children}</AnimatePresenceRoot>
        </SmoothScrolling>
        <SpeedInsights />
      </body>
    </html>
  );
}
